In [1]:
import numpy as np

In [25]:
Q = np.array([[0,1/2],[0,0]])
I = np.identity(2)
np.linalg.inv(I-Q)

array([[1. , 0.5],
       [0. , 1. ]])

In [31]:
Q = np.array([[1/2,0],[1,0]])
I = np.identity(2)
np.linalg.inv(I-Q)

array([[ 2., -0.],
       [ 2.,  1.]])

In [32]:
Q = np.array([[1/3,1/3,0],[1/3,0,0],[1,0,0]])
I = np.identity(3)
np.linalg.inv(I-Q)

array([[1.80000000e+00, 6.00000000e-01, 2.22044605e-16],
       [6.00000000e-01, 1.20000000e+00, 5.55111512e-17],
       [1.80000000e+00, 6.00000000e-01, 1.00000000e+00]])

array([[1.5 , 0.5 , 0.75],
       [1.5 , 1.5 , 0.75],
       [0.  , 0.  , 1.5 ]])